version: "3.8"
services:
  proxy:
    container_name: proxy
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./appdata/conf.d:/etc/nginx/conf.d
      - ./appdata/certbot/conf:/etc/letsencrypt
      - ./appdata/certbot/data:/var/www/certbot
      - ./www/:/var/www/
    networks:
      - vault-network

  vault-server:
    image: vault:latest
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=http://172.21.0.10:8200
      - VAULT_API_ADDR=http://172.21.0.10:8200
      - VAULT_ADDRESS=http://172.21.0.10:8200
    cap_add:
      - IPC_LOCK
    platform: linux/x86_64
    networks:
      vault-network:
        ipv4_address: 172.21.0.10
        aliases:
          - vault-server
    volumes:
      - ./vault/config:/vault/config
      - ./vault/data:/vault/data
      - ./vault/policies:/vault/policies
    entrypoint: vault server -config=/vault/config/vault.json
   
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email chohh@trevari.co.kr --agree-tos --no-eff-email -d vault.trevari.co.kr
    volumes:
      - ./appdata/certbot/conf:/etc/letsencrypt
      - ./appdata/certbot/logs:/var/log/letsencrypt
      - ./appdata/certbot/data:/var/www/certbot
    depends_on:
      - proxy

networks:
  vault-network:
    ipam:
      config:
        - subnet: 172.21.0.0/24
